### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Sun-Shine2**
Let's discuss about some changes on frontend.

### CODE REVIEW

**Comment by patronus5** [comment]
Do you think this change is needed?

**Comment by Sun-Shine2** [comment]
> Do you think this change is needed?

I think so because current interface is not looks good.

**Comment by patronus5** [comment]
> > Do you think this change is needed?
> 
> I think so because current interface is not looks good.

I don't think so. Let me explain why you think so.

**Comment by Sun-Shine2** [comment]
> > > Do you think this change is needed?
> > 
> > 
> > I think so because current interface is not looks good.
> 
> I don't think so. Let me explain why you think so.

You used tailwindCSS for css. That's good. But now it is not pixel perfect. So it have to be modified.

**Comment by patronus5** [comment]
> > > > Do you think this change is needed?
> > > 
> > > 
> > > I think so because current interface is not looks good.
> > 
> > 
> > I don't think so. Let me explain why you think so.
> 
> You used tailwindCSS for css. That's good. But now it is not pixel perfect. So it have to be modified.

Okay.

**Pull request merged**
